version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}  # .env 파일의 변수 참조
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    volumes:
      - minimalest-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    image: minimalest-api
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  minimalest-mysql-data:
