spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 30
        format_sql: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      region:
        static: ${AWS_S3_REGION}
      bucket:
        name: ${AWS_S3_BUCKET}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.web: WARN
    kr.minimalest.core: INFO


auth:
  success:
    redirect-uri: http://localhost:5173/

  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: 1800000 #ms (1000 * 60 * 30) : 30분
    refresh-expiration: 604800000 #ms (1000 * 60 * 60 * 24 * 7) : 7일
    clock-skew-seconds: 120 #s 120초

  oauth:
    google:
      client_id: ${OAUTH_GOOGLE_CLIENT_ID}
      client_secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
      redirect_uri: ${OAUTH_GOOGLE_REDIRECT_URI}
      token_uri: https://oauth2.googleapis.com/token
      resource_uri: https://www.googleapis.com/oauth2/v2/userinfo
