spring:
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Seoul

file:
  proxy:
    url: /api/file/proxy

springdoc:
  paths-to-match: /api/**

server:
  http2:
    enabled: true
  ssl:
    enabled: true
